apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m" #200 millicpu (.2 cpu, 20%)
      readinessProbe:
        httpGet:
          port: 80
          path: /index.html
        initialDelaySeconds: 3
        periodSeconds: 5
        failureThreshold: 1
      livenessProbe:
        httpGet:
          port: 80
          path: /index.html
        initialDelaySeconds: 15
        periodSeconds: 5
        failureThreshold: 1