apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:  # gdzie dane będą
    path: /tmp/data/db
  storageClassName: local-storage # nazwa storage klasy
  nodeAffinity:  # przyłaczenie volumu do konkretnego noda
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop  # my node name