services:
  node-app-v1:
    image: node-app:1.0
    build:
      context: ./v1
      dockerfile: Dockerfile
  node-app-v2:
    image: node-app:2.0
    build:
      context: ./v2
      dockerfile: Dockerfile
  node-app-v3:
    image: node-app:3.0
    build:
      context: ./v3
      dockerfile: Dockerfile
  node-app-v4:
    image: node-app:4.0
    build:
      context: ./v4
      dockerfile: Dockerfile