apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello2
spec:
  schedule: "* * * * *"
  startingDeadlineSeconds: 30
  concurrencyPolicy: Allow  # mogą 2 naraz, Replace -zabija stary i robi nowy
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: alpine:latest
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster; sleep 600
          restartPolicy: OnFailure