apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  backoffLimit: 4
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: script
        image: alpine:latest
        command: ["echo",  "yolo"]
      restartPolicy: Never
