apiVersion: batch/v1
kind: CronJob
metadata:
  name: parallel
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: ctr
            image: alpine:latest
            command: ['sh', '-c', 'echo "Lets smash the CKAD" && sleep 25']