apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:  # przypięcie serwisu do poda
    app: backend
  ports:
    - port: 8001  # zew
      targetPort: 8000    # wew