apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  selector:  # przypięcie serwisu do poda
    app: db
  ports:
    - port: 5432 # zew
      targetPort: 5432    # wew