apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP
  selector:  # przypięcie serwisu do poda
    app: my-nginx
  ports:
    - port: 80  # zew
      targetPort: 80    # wew
