apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:  # przypięcie serwisu do poda
    app: my-nginx
  ports:
    - port: 80  # zew
      targetPort: 80    # wew
      nodePort: 30001 # statyczny port noda