apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary-deploy
  name: canary-deploy
spec:
  replicas: 1
  selector:
    matchLabels: # szuka podów pasujących do app: z templates
      track: canary
      app: customer-app
  template:
    metadata:
      labels:
        track: canary
        app: customer-app
    spec:
      containers:
      - image: ckad:canary
        name: canary
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80 # z docker file
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
