apiVersion: v1
kind: Service
metadata:
  name: public-service
  labels:
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: customer-app
  ports:
    - port: 80 # na zew.
      targetPort: 80 # wew.